### ISSUE TITLE
Popularimeter rating is not set correctly in files

### ISSUE THREAD

**Issue by ufleisch** [gnumdk/lollypop-portal#1]
The rating is not set correctly in ID3v2 tags. I suppose that the intention was to set a Popularimeter (POPM) frame using kid3-cli. However, using `set pop: %s` a TXXX frame with description `pop` is set. If you want to set a POPM frame, you have to use the identification POPM instead (the reason why an internal ID has to be used is because POPM is not a unified frame of Kid3).

```
--- lollypop-portal.orig	2016-12-11 22:25:53.000000000 +0100
+++ lollypop-portal	2017-01-02 10:46:31.449088376 +0100
@@ -173,7 +173,7 @@
                             GLib.SpawnFlags.SEARCH_PATH, None)
 
     def SetPopularity(self, pop, f):
-        argv = ["kid3-cli", "-c", "set pop: %s" % pop, f, None]
+        argv = ["kid3-cli", "-c", "set POPM %s" % pop, f, None]
         GLib.spawn_sync(None, argv, None,
                         GLib.SpawnFlags.SEARCH_PATH, None)
 
```

**Comment by gnumdk** [comment]
Send me a pull request next time, thanks!
